baseURL: "/"
languageCode: "es-co"
title: "Red Colombiana de Fototrampeo"
theme: "hugo-creative-theme"
googleAnalytics: "As_PN292vEIkPRWjpIONnEkNX05fcEZFsDoJRCKY5MY"

params:
  name: "Diego J. Lizcano"
  description: "Red Colombiana de Fototrampeo, camera trap, trampa camara"
  favicon: "favicon.ico"

  navigation:
    brand: "Red Colombiana de Fototrampeo"
    links:
      about: "La Red"
      services: "Servicios"
      portfolio: "Foto del Mes"
      contact: "Contacto"
      aside: "Mapa"

  hero:
    slogan: "Red Colombiana de Fototrampeo"
    subtitle: "Una herramienta para conectar a quienes muestrean vertebrados terrestres en Colombia"
    buttonText: "Encuentra más detalles"

  about:
    headline: "Qué hace la red?"
    description: "Funciona como articulación formal para la consolidación de información en la que participaron 20 instituciones y 45 investigadores. Los retos para el fototrampeo en Colombia están centrados en aumentar la cobertura geográfica y taxonómica, homogenizar y proponer nuevos diseños de muestreo y análisis, reducir los tiempos en el procesamiento de datos y buscar los mecanismos para incidir de manera efectiva en los tomadores de decisiones, quienes requieren de información útil y especializada para el diseño de estrategias de conservación y manejo. Recientemente nos hemos movido a wildlifeinsights."

  services:
    headline: "Qué beneficios presta la red?"
    list:
      - icon: "fas fa-binoculars"
        title: "Conocer otras iniciativas"
        description: "Entérate del trabajo que se realiza y ayúdanos a construir comunidad."
      - icon: "fa-bar-chart"
        title: "Análisis conjuntos"
        description: "Úsenos como herramienta para encontrar los datos que necesita!"
      - icon: "fa-newspaper-o"
        title: "Estar actualizado"
        description: "Nosotros brindamos información y proporcionamos conocimientos."
      - icon: "fa-database"
        title: "Visibilizar sus datos"
        description: "Tienes que hacer tus datos disponibles en estos días!"

  portfolio:
    modal:
      client: "Proyecto"
      date: "Fecha"
      category: "Genero"
      buttonText: "Cerrar"

  aside:
    headline: "Dónde hay datos y quién los tomó"
    button:
      text: "Ir a la iniciativa en WildlifeInsights"
      link: "https://app.wildlifeinsights.org/initiatives/2000155/Red-Colombiana-de-Fototrampeo"

  contact:
    headline: "Contáctenos y unase a la red!"
    description: "Angélica Diaz-Pulido y Diego J. Lizcano"
    email: "adiaz@humboldt.org.co"
